- platform: xiaomi_miio_airpurifier
  host: 192.168.2.16
  token: !secret xiaomi_deerma_token
  name: "xiaomi_deerma"
  model: deerma.humidifier.jsq

- platform: xiaomi_miio_airpurifier
  host: 192.168.2.15
  token: !secret xiaomi_airpurifier_token
  name: "xiaomi_airpurifier"
  model: zhimi.airpurifier.mb3
