- platform: xiaomi_miio_airpurifier
  host: 192.168.2.16
  token: 6bbee826f815af09173bba9ae10cae55
  name: "xiaomi_deerma"
  model: deerma.humidifier.jsq

  #  NAME:     Mi Smart Antibacterial Humidifier
  #  ID:       245086508
  #  MAC:      64:90:C1:C8:E7:AC
  #  IP:       192.168.2.16
  #  TOKEN:    6bbee826f815af09173bba9ae10cae55
  #  MODEL:    deerma.humidifier.jsq
